import { memo, ReactNode } from "react"
import Head from 'next/head'
import Link from 'next/link'
import styled from 'styled-components'
import Navigation from "../../components/Navigation"
import Header from "../../components/Header"
import Footer from "../../components/Footer"

const StyledLayout = styled.div`
  align-items: center;
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  min-height: 100vh;

  main {
    align-self: stretch;
    flex-grow: 1;
  }
`

interface SiteLayoutProps {
  children: ReactNode
}

function SiteLayout({ children }: SiteLayoutProps) {
  return (
    <StyledLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        Logo
      </Header>

      <Navigation>
        <ul>
          <li>
            <Link href="/">Home</Link>
          </li>
          <li>
            <Link href="/blog">Blog</Link>
          </li>
        </ul>
      </Navigation>

      {children}

      <Footer>
        mah footer
      </Footer>
    </StyledLayout>
  )
}

SiteLayout.whyDidYouRender = true

export default memo(SiteLayout)
